// KIWI Security Constants & System Configuration
// RFC 8032 Ed25519 Cryptographic Trust Anchor

/// Authoritative KIWI Root CA Public Key (32-byte Ed25519 in 64-char lowercase hex)
/// Generated by offline provisioning tool: generate_root_key.py
/// Safe to hardcode and distribute with the mobile application.
const String kKiwiRootPublicKeyHex =
    "e0db24a70d30b685e1cad73648f1f0b690966bfc05bf6d3900f151cdd46b312a";

/// Canonical Payload Prefixes for parser-independent signature validation
const String kCertCanonicalPrefix = "KIWI-CERT:v1:";
const String kAuthChallengePrefix = "KIWI-AUTH:v1:";
const String kClientVerifyPrefix = "KIWI-CLIENT:v1:";

/// Gateway Network Endpoints & Timeouts
const String kDefaultGatewayHost = "192.168.4.1";
const int kDefaultGatewayPort = 80;
const String kMutualAuthEndpoint = "/api/v1/mutual_auth";
const String kClientVerifyEndpoint = "/api/v1/client_verify";
const String kProvisionStatusEndpoint = "/api/v1/provision/status";

/// Strict 2000ms handshake timeout requirement
const int kHandshakeTimeoutMs = 2000;

/// Default SoftAP identification
const String kTargetSoftApSsid = "KIWI-Secure-Zone";

/// Secure Storage & Preferences Keys
const String kSecurePhonePrivKeyKey = "kiwi_phone_ed25519_priv_seed";
const String kSecurePhonePubKeyKey = "kiwi_phone_ed25519_pub_hex";
const String kThreatLogPrefsKey = "kiwi_threat_log_v1";
const String kCachedCrlPrefsKey = "kiwi_cached_crl_v1";
const String kCrlLastSyncPrefsKey = "kiwi_crl_last_sync_timestamp";

/// Offline Revocation Staleness Threshold: 7 days in seconds
const int kCrlStalenessThresholdSeconds = 7 * 24 * 60 * 60;
